[versions]
leakcanaryAndroidVersion = "2.14"
xposedVersion = "82"
cameraVersion = "1.4.2"
converterGsonVersion = "3.0.0"
gson ="2.13.2"
retrofitVersion = "3.0.0"
coreKtx = "1.16.0"
firebaseBomVersion = "33.16.0"
flexboxVersion = "3.0.0"
junit = "4.13.2"
junitVersion = "1.3.0"
appcompat = "1.7.1"
lifecycleLivedataKtxVersion = "2.9.2"
loggingInterceptorVersion = "5.1.0"
#noinspection GradleDependency
material = "1.6.1"
aabresguardPluginVersion = "0.1.10"
roomVersion = "2.7.2"
pagingVersion = "3.3.6"
okhttpBom = "4.12.0"
documentFileVersion = "1.1.0"
rxandroidVersion = "3.0.2"
rxjavaVersion = "3.1.11"
xor = "5.0.0"
stringfogGradlePlugin = "5.2.0"
glide = "5.0.5"
swiperefresh = "1.1.0"
adjustAndroidVersion = "5.4.3"
mmkv = "2.2.3"
lottieVersion = "6.6.9"
playServicesAdsVersion = "24.6.0"
activityVersion = "1.10.1"
opencvVersion = "4.12.0"

[libraries]
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraVersion" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraVersion" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraVersion" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraVersion" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "roomVersion" }
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "pagingVersion" }

leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroidVersion" }
xposed = { module = "de.robv.android.xposed:api", version.ref = "xposedVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGsonVersion" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexboxVersion" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttpBom" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentFileVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBomVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtxVersion" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleLivedataKtxVersion" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleLivedataKtxVersion" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptorVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroidVersion" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjavaVersion" }
xor = { module = "com.github.megatronking.stringfog:xor", version.ref = "xor" }
aabresguard-plugin = { module = "com.bytedance.android:aabresguard-plugin", version.ref = "aabresguardPluginVersion" }
stringfogGradlePlugin = { module = "com.github.megatronking.stringfog:gradle-plugin", version.ref = "stringfogGradlePlugin" }
swiperefresh-layout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefresh" }
mmkv = { module = "com.tencent:mmkv-static", version.ref = "mmkv" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottieVersion" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAdsVersion" }
adjust-android = { module = "com.adjust.sdk:adjust-android", version.ref = "adjustAndroidVersion" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activityVersion" }
opencv = { module = "org.opencv:opencv", version.ref = "opencvVersion" }


[bundles]
room = [
    "androidx-room-ktx",
    "androidx-room-runtime",
    "androidx-room-paging",
    "androidx-paging-runtime",
]

